name: Build Skia - Windows x64

on:
  push:
    tags:
      - '*'


jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Install skia-builder
      run: |
        pip install .

    - name: Setup skia environment for Windows
      run: |
        skia-builder setup-env

    - name: Build skia for Windows
      run: |
        skia-builder build --target-cpu=x64 --archive

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4.4.3
    #   with:
    #     name: skia-artifacts
    #     path: |
    #       output/windows-x64/windows-x64.tar.gz

    - name: Upload artifacts to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.2.1
      with:
        name: ${{ github.ref_name }}
        files: |
          output/windows-x64/windows-x64.tar.gz
        draft: true
