name: Build Skia - Android (arm, arm64, x64, x86)

on:
  push:
    tags:
      - 'v[0-9][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]*'

jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Install skia-builder
      run: |
        pip install .

    - name: Setup skia environment for windows + android
      run: |
        skia-builder setup-env --sub-env=Android

    - name: Build skia for android (arm, arm64, x64, x86)
      run: |
        skia-builder build --sub-env=Android --target-cpu=arm --archive
        skia-builder build --sub-env=Android --target-cpu=arm64 --archive
        skia-builder build --sub-env=Android --target-cpu=x64 --archive
        skia-builder build --sub-env=Android --target-cpu=x86 --archive

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4.4.3
    #   with:
    #     name: skia-artifacts
    #     path: output/windows-x64.tar.gz

    - name: Upload artifacts to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.1.0
      with:
        name: ${{ github.ref_name }}
        files: |
          output/android-arm/android-arm.tar.gz
          output/android-arm64/android-arm64.tar.gz
          output/android-x64/android-x64.tar.gz
          output/android-x86/android-x86.tar.gz
        draft: true
      # env:
      #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
